import type { Metadata } from "next";
import "./globals.css";
import Header from "./_component/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <Header/>
        <main className={'w-full h-full min-h-[calc(100dvh-54px)] '}>
          <div id="portal-root"></div>
            {children}
        </main>
      </body>
    </html>
  );
}
